//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_Control_Tower
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITControlTowerEntities : DbContext
    {
        public ITControlTowerEntities()
            : base("name=ITControlTowerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<failed_jobs> failed_jobs { get; set; }
        public virtual DbSet<migration> migrations { get; set; }
        public virtual DbSet<NewHire> NewHires { get; set; }
        public virtual DbSet<post> posts { get; set; }
        public virtual DbSet<TechPartner> TechPartners { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<password_resets> password_resets { get; set; }
    }
}
